apiVersion: v1
kind: Service
metadata:
  labels:
    name: git
  name: git
  namespace: sample-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    name: web
  - port: 22
    protocol: TCP
    targetPort: 1022
    name: gitssh
  selector:
    name: gogs
